name: NatviesChatColor
version: 1.0
main: mrnatvies.natvieschatcolor.NatviesChatColor
api-version: 1.16
commands:
  chatcolor:
    description: Изменение цвета чата
    usage: /chatcolor <цвет | clear | reload>
permissions:
  chatcolor.use:
    description: Позволяет использовать команду /chatcolor
    default: true
  chatcolor.clear:
    description: Позволяет очищать цвет чата
    default: true
  chatcolor.reload:
    description: Позволяет перезагружать конфигурацию
    default: op